<a href="https://colab.research.google.com/github/gksdydcks/Ai/blob/main/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import torch
torch.__version__

'2.5.1+cu121'

In [ ]:
!pip install torchvision torchaudio


#초기화 : 텐서에 특정값을 채워서 생성

#### 1-1 초기화 되지 않은 Tensor

In [ ]:
import cv2
import numpy as np
x = torch.empty(4,2)  #2d텐서 (row,column)
print(x)

tensor([[ 5.4689e-18,  4.4267e-41],
        [ 5.4689e-18,  4.4267e-41],
        [-2.8000e+04,  3.1114e-41],
        [-2.8000e+04,  3.1114e-41]])


#### 1-2 상수로 초기화 된 Tensor

In [ ]:
x = torch.zeros(4,2, dtype=torch.long)  #데이터 타입 지정
y = torch.ones(2,4, dtype=torch.double)
print(x,y)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


#### 1-3 무작위로 초기화된 Tensor

In [ ]:
x=torch.rand(4,2)
y=torch.randn(2,3)
print(x,y)

tensor([[0.8186, 0.2628],
        [0.3714, 0.7915],
        [0.2621, 0.1282],
        [0.7787, 0.9399]]) tensor([[-0.1942, -0.3488, -0.7999],
        [-0.7505,  1.4071,  0.6067]])


#### 1-4. 직접 입력한 값으로 초기화

In [ ]:
x = torch.tensor([1,2.5])
print(x)

tensor([1.0000, 2.5000])


#### 1-5. Numpy 배열로 부터 초기화

In [ ]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)

b = torch.tensor([1,2,3,4,5])#numpy array로 변환
new_nd = b.numpy()
new_nd[2] = 100 #[2번째 바꿈]
print(new_nd)


[  1   2 100   4   5]


#### 1-6. 특정 텐서와 같은 타입, 무작위로 값을 채움

In [ ]:
a =torch.ones(3,4,dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float)
#b = torch.zeors_like(a, dtype=torch.float) #0출력
print(b)

tensor([[0.2113, 0.2767, 0.5380, 0.9465],
        [0.3174, 0.0388, 0.9520, 0.1931],
        [0.5190, 0.2859, 0.5029, 0.9802]])


In [ ]:
!git add test1.ipynb


fatal: not a git repository (or any of the parent directories): .git


#### 1-7. Tensor의 속성

In [ ]:
tensor = torch.rand(3,4)
print(tensor.size())#모양
print(tensor.shape)#모양
print(tensor.dtype)#자료형
print(tensor.device)#장치

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


#### 1-8. 특정 타입의 Tensor 생성

In [ ]:
tensor = torch.rand(3,4,dtype=torch.float64)
print(tensor.dtype)
ft = torch.FloatTensor([1,2,3])
print(ft.dtype)

tensor = torch.tensor([1,2,3], dtype=torch.int32)
print(tensor.dtype)


torch.float32
torch.int32


#### 1-9. 데이터 타입 캐스팅

In [ ]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())
int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


#### 1-10. CUDA Tensor

In [ ]:
print(torch.cuda.is_available())

True


In [ ]:
tensor = torch.rand(3,4,dtype=torch.float64)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor.to(device)
tensor.device

device(type='cpu')

#### 1-11. 다차원 Tensor 표현

#### 1-11-1. OD Tensor(Scalar)
  - 하나의 값을 담고 있는 텐서

In [ ]:
t0=torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


#### 1-11-2. 1D Tensor(Vector)
- 일종의 값을 저장한 리스트와 유사한 *텐서*

In [ ]:
 t1 = torch.tensor([1,2,3])
 print(t1.ndim)
 print(t1.shape)
 print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-2. 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재


In [ ]:
 t2 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
 print(t2.ndim)
 print(t2.shape)
 print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### 1-11-3. 3D Tensor(*Cube*)
- 큐브와 같은 형태로 세개의 축이 존재

In [ ]:
t3 = torch.tensor([[[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]]
                  ])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([4, 3, 2])
tensor([[[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]]])


#### 1-11-4. 4D Tensor
- 4개의 축 존재


In [ ]:
t4 = torch.rand(2,3,4,5)
t4

tensor([[[[0.3034, 0.2631, 0.0250, 0.4286, 0.8969],
          [0.0429, 0.5368, 0.2864, 0.6344, 0.9918],
          [0.0254, 0.3454, 0.7027, 0.3186, 0.2346],
          [0.4061, 0.6083, 0.9374, 0.1555, 0.4353]],

         [[0.5972, 0.4973, 0.3411, 0.7257, 0.6188],
          [0.7151, 0.8476, 0.0340, 0.4270, 0.6186],
          [0.7974, 0.8785, 0.7955, 0.8884, 0.4245],
          [0.1233, 0.3314, 0.7009, 0.6173, 0.5951]],

         [[0.4936, 0.4978, 0.1600, 0.9402, 0.1364],
          [0.8061, 0.6595, 0.7882, 0.5567, 0.6980],
          [0.1898, 0.5143, 0.8063, 0.1858, 0.4885],
          [0.9560, 0.1508, 0.7027, 0.9990, 0.1793]]],


        [[[0.0145, 0.8243, 0.4806, 0.6317, 0.2515],
          [0.0114, 0.6918, 0.0777, 0.1267, 0.4450],
          [0.8993, 0.6438, 0.5002, 0.0321, 0.1639],
          [0.5083, 0.0759, 0.1013, 0.5782, 0.4824]],

         [[0.8090, 0.6119, 0.1581, 0.6472, 0.3169],
          [0.9588, 0.8314, 0.9336, 0.3471, 0.5976],
          [0.0488, 0.4728, 0.6128, 0.4610, 0.2329],
  