<a href="https://colab.research.google.com/github/gksdydcks/Ai/blob/main/02_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 02. 텐서의 연산

In [ ]:
import torch

### 2-1. Tensor 연산

In [ ]:
tensor = torch.rand(2,2)
print(tensor)
tensor = tensor *2
print(tensor)
tensor = tensor +1
print(tensor)

tensor([[0.5002, 0.7559],
        [0.9569, 0.1993]])
tensor([[1.0004, 1.5119],
        [1.9137, 0.3986]])
tensor([[2.0004, 2.5119],
        [2.9137, 1.3986]])


더하기

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y)
print(x,y)
print(x+y)

tensor([[0.0127, 0.9320],
        [0.3455, 0.6370]]) tensor([[0.2265, 0.0240],
        [0.0174, 0.8777]])
tensor([[0.2392, 0.9559],
        [0.3629, 1.5147]])


inplace 바꿔치기 연산

In [ ]:
add = torch.add(x,y)
print(add)
y.add_(x)
print(y)

tensor([[0.2518, 1.8879],
        [0.7084, 2.1516]])
tensor([[0.2518, 1.8879],
        [0.7084, 2.1516]])


빼기

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x,y)
print(sub)

tensor([[0.0679, 0.1698],
        [0.8434, 0.7717]]) tensor([[0.8220, 0.3276],
        [0.2178, 0.1923]])
tensor([[-0.7540, -0.1578],
        [ 0.6256,  0.5793]])


곱하기


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x,y)
print(mul)

tensor([[0.2400, 0.2909],
        [0.9753, 0.8000]]) tensor([[0.4358, 0.3228],
        [0.3077, 0.1779]])
tensor([[0.1046, 0.0939],
        [0.3001, 0.1423]])


나누기

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x,y)
print(x,y)
print(div)

tensor([[0.9071, 0.7905],
        [0.7967, 0.2905]]) tensor([[0.8143, 0.6256],
        [0.5598, 0.7965]])
tensor([[1.1140, 1.2637],
        [1.4231, 0.3647]])
