<a href="https://colab.research.google.com/github/gksdydcks/Ai/blob/main/03_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 3.Tensor의 조작

### 3-1. 인덱싱 슬라이싱
- numpy처럼 활용

In [1]:
import torch

In [7]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1])
print(tensor[0,:])

a = torch.tensor([1,2,3,4,5])
print(a[-2:])

b=torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9]])
c = b[b>5]
d= b[b%2 == 0]
e=b[[0,1],[1,2]] #0행의 첫번째와 1행의 2번째 불러옴
print(e)


tensor(2)
tensor([1, 2])
tensor([4, 5])


### 3-2. Tensor의  크기 모양변경

-

In [9]:
t = torch.rand(4,5)
print(t)
x=t.view(5,4)
print(x)

y=t.view(10,-1)
print(y)

tensor([[0.4863, 0.8443, 0.2583, 0.5799, 0.0442],
        [0.3014, 0.8844, 0.0214, 0.3064, 0.5968],
        [0.8048, 0.7189, 0.8676, 0.4105, 0.6653],
        [0.9405, 0.4754, 0.9292, 0.9319, 0.4850]])
tensor([[0.4863, 0.8443, 0.2583, 0.5799],
        [0.0442, 0.3014, 0.8844, 0.0214],
        [0.3064, 0.5968, 0.8048, 0.7189],
        [0.8676, 0.4105, 0.6653, 0.9405],
        [0.4754, 0.9292, 0.9319, 0.4850]])
tensor([[0.4863, 0.8443],
        [0.2583, 0.5799],
        [0.0442, 0.3014],
        [0.8844, 0.0214],
        [0.3064, 0.5968],
        [0.8048, 0.7189],
        [0.8676, 0.4105],
        [0.6653, 0.9405],
        [0.4754, 0.9292],
        [0.9319, 0.4850]])


### 3-3 Tensor의 숫자값 얻기

In [16]:
x= torch.rand(1)
print(x)
print(x.item())

tensor([0.5188])
0.5187618136405945


### 3-4 차원 축소와 증가
 - torch.squeeze() : 크기가 1인 차원을 축소

In [18]:
x = torch.rand(1,3,3)
print(x)
print(x.shape)

y=  torch.squeeze(x)
print(y)
print(y.shape)


tensor([[[0.0497, 0.5500, 0.0168],
         [0.7097, 0.8218, 0.9173],
         [0.2792, 0.9560, 0.7927]]])
torch.Size([1, 3, 3])
tensor([[0.0497, 0.5500, 0.0168],
        [0.7097, 0.8218, 0.9173],
        [0.2792, 0.9560, 0.7927]])
torch.Size([3, 3])


### 3-5. 차원 증가(생성)
- torch.unsqueeze : 지정한 위치에 새로운 차원 생성

In [22]:
x = torch.rand(3,3,3)
print(x)
print(x.shape)

y=  torch.unsqueeze(x,0)
print(y)
print(y.shape)

tensor([[[0.1518, 0.9234, 0.3432],
         [0.8946, 0.0379, 0.1372],
         [0.3016, 0.1513, 0.1456]],

        [[0.4831, 0.0544, 0.4661],
         [0.8595, 0.5220, 0.7727],
         [0.4571, 0.3976, 0.7711]],

        [[0.9069, 0.7917, 0.5761],
         [0.0623, 0.2175, 0.8631],
         [0.6292, 0.7107, 0.5361]]])
torch.Size([3, 3, 3])
tensor([[[[0.1518, 0.9234, 0.3432],
          [0.8946, 0.0379, 0.1372],
          [0.3016, 0.1513, 0.1456]],

         [[0.4831, 0.0544, 0.4661],
          [0.8595, 0.5220, 0.7727],
          [0.4571, 0.3976, 0.7711]],

         [[0.9069, 0.7917, 0.5761],
          [0.0623, 0.2175, 0.8631],
          [0.6292, 0.7107, 0.5361]]]])
torch.Size([1, 3, 3, 3])


### 3-6. Tensor간 결합
- torch,stack() : 동일한 형식의 텐서를 새롭게 그룹화
- 새로운 차원 생성

In [26]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])

z = torch.stack((x,y))
print(z)
print(z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- torch.cat(): 하나의 텐서로 결합
- 새로운 차원 생성 x

In [30]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])

z = torch.cat((x,y),dim=0)  #행기준 합치기
z_1 = torch.cat((x,y),dim=1) #열기준 합치기
print(z)
print(z.shape)
print(z_1)
print(z_1.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])


## 3-7 Tensor 나누기


- torch.chunk : 텐서를 몇개로 나눌지 지정
- 나누어 떨어지지 않으면 나머지 조각은 크기 다를 수 있음

In [39]:
t = torch.rand(5,3)
print(t)

a,b,c = torch.chunk(t,3,dim=0)#행 기준 3개로 쪼갬
a_1,b_1,c_1 = torch.chunk(t,3,dim=1)#열기준 3개로 쪼갬
print(a)
print(b)
print(c)
print(a_1)
print(b_1)
print(c_1)


tensor([[0.3951, 0.9799, 0.1646],
        [0.8149, 0.4743, 0.4241],
        [0.3730, 0.4215, 0.9575],
        [0.1239, 0.3301, 0.4051],
        [0.2452, 0.2753, 0.3434]])
tensor([[0.3951, 0.9799, 0.1646],
        [0.8149, 0.4743, 0.4241]])
tensor([[0.3730, 0.4215, 0.9575],
        [0.1239, 0.3301, 0.4051]])
tensor([[0.2452, 0.2753, 0.3434]])
tensor([[0.3951],
        [0.8149],
        [0.3730],
        [0.1239],
        [0.2452]])
tensor([[0.9799],
        [0.4743],
        [0.4215],
        [0.3301],
        [0.2753]])
tensor([[0.1646],
        [0.4241],
        [0.9575],
        [0.4051],
        [0.3434]])


- torch.split() : 텐서의 크기 기준으로 나눔
-

In [47]:
t = torch.rand(6,3)
print(t)

x,y = torch.split(t,3,dim=0)
print(x)
print(y)

a = torch.tensor([1,2,3,4,5])

a_1 = torch.split(a,[2,2,1],dim=0)
print(a)
print(a_1)


tensor([[0.5178, 0.7135, 0.9936],
        [0.8515, 0.6654, 0.4625],
        [0.5759, 0.7224, 0.5657],
        [0.6037, 0.5269, 0.3500],
        [0.3471, 0.1976, 0.4074],
        [0.8069, 0.7260, 0.4547]])
tensor([[0.5178, 0.7135, 0.9936],
        [0.8515, 0.6654, 0.4625],
        [0.5759, 0.7224, 0.5657]])
tensor([[0.6037, 0.5269, 0.3500],
        [0.3471, 0.1976, 0.4074],
        [0.8069, 0.7260, 0.4547]])
tensor([1, 2, 3, 4, 5])
(tensor([1, 2]), tensor([3, 4]), tensor([5]))
