<a href="https://colab.research.google.com/github/gksdydcks/Ai/blob/main/quiz4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print("setting complete.")

setting complete.


### 문제1
- 2차원 텐서 [[1, 2, 3], [4, 5, 6]]를 3x2 텐서로 변환해서 출력하세요.

In [27]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = a.view(3, 2)
print(b)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### 문제2
- 단일 값 텐서 tensor(42)에서 값을 추출하고 데이터 타입을 확인해서 출력하세요.
- (1) 값을 추출하고
- (2) 데이터 타입을 확인하세요.

In [4]:
a = torch.tensor(42)
print(a.item())
print(a.dtype)


42
torch.int64


### 문제 3
- 3차원 텐서 [[[1, 2, 3]]]에서 크기가 1인 차원을 제거해서 출력하세요.

In [31]:
a = torch.tensor([[[1, 2, 3]]])
print(a.shape)
b = a.squeeze()
print(b)
print(b.shape)

torch.Size([1, 1, 3])
tensor([1, 2, 3])
torch.Size([3])


### 문제 4
- 1차원 텐서 [1, 2, 3]에 새로운 차원을 추가하여 2차원 텐서로 만들어 출력하세요.

In [34]:
a = torch.tensor([1, 2, 3])
b = torch.unsqueeze(a,dim=0)

print(b)

tensor([[1, 2, 3]])


### 문제 5
- 두 텐서 a = [1, 2]와 b = [3, 4]를 쌓아 2x2 텐서를 생성해서 출력하세요.


In [10]:

a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = torch.stack((a, b))
print(c)

tensor([[1, 2],
        [3, 4]])


### 문제 6
- 두 텐서 a = [[1, 2], [3, 4]]와 b = [[5, 6], [7, 8]]를 열 방향으로 연결해서 출력하세요.

In [35]:
a = torch.tensor([[1, 2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
c = torch.cat((a, b),dim = 1)
print(c)


tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### 문제 7
- 텐서 [[1, 2, 3], [4, 5, 6]]를 2개의 조각으로 나눠서 출력해보세요. (행 기준).

In [36]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.chunk(a,2, dim =0)
print(b)

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]))


### 문제8
- 텐서 [1, 2, 3, 4, 5]를 각각 2, 2, 1의 크기로 나눠서 출력해보세요.

In [38]:
a = torch.tensor([1,2,3,4,5])
x,y,z = torch.split(a,[2,2,1],dim=0)
b= torch.split(a,[2,2,1],dim=0)
print(b)
print(x,y,z)

(tensor([1, 2]), tensor([3, 4]), tensor([5]))
tensor([1, 2]) tensor([3, 4]) tensor([5])


### 문제9
- 텐서 [[1, 2], [3, 4], [5, 6]]에서:
- dim=1 기준으로 크기 1씩 나누세요.
- 각각의 조각을 새로운 축에 쌓은 후 출력해보세요.

In [20]:
# 여기에 코드를 작성합니다
# 1. 열 기준으로 크기 1씩 나누기
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.split(a,1,dim=1)
print(b)
# 2. 새로운 축에 쌓기
c= torch.stack(b)
print(c)


(tensor([[1],
        [3],
        [5]]), tensor([[2],
        [4],
        [6]]))
tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])


### 문제10
- 다음 텐서를 활용해서 아래 문제를 해결해보세요
  ```
  a = torch.tensor([[1, 2], [3, 4]])
  b = torch.tensor([[5, 6], [7, 8]])
  ```

1. 두 텐서를 열 기준으로 연결하고 결과를 출력하세요.
2. 연결된 텐서를 크기 `(4, 2)`로 변환하세요.
3. 변환된 텐서를 2개의 조각으로 나누고, 각 조각을 0번 축으로 스택하여 출력하세요.


In [41]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
# 여기에 코드를 작성합니다
# 1. 열 기준으로 병합
a = torch.cat((a,b),dim =1)
print(a)
# 2. 크기 (4, 2)로 변환
b = a.view(4,2)
print(b)
# 3. 2개의 조각으로 나누고
c = torch.chunk(b,2,dim=0)
print(c)
# 4. 0번 축으로 스택
d= torch.stack(c)
print(d)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [5, 6],
        [3, 4],
        [7, 8]])
(tensor([[1, 2],
        [5, 6]]), tensor([[3, 4],
        [7, 8]]))
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
