<a href="https://colab.research.google.com/github/gksdydcks/Ai/blob/main/quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [37]:
import torch
x = torch.tensor([2, 4, 6])
add =(x + 5)
sub = (x - 3)
print(add)
print(sub)

tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [12]:

a = torch.rand(3,3)
b = torch.rand(3,3)

add = torch.add(a,b)
sub = torch.sub(a,b)
mul = torch.mul(a,b)
div = torch.div(a,b)

print(add)
print(sub)
print(mul)
print(div)

tensor([[1.6817, 0.3730, 0.2794],
        [0.6580, 0.7746, 0.2674],
        [0.9898, 0.4007, 0.2707]])
tensor([[-0.0678, -0.1538,  0.2767],
        [ 0.2359,  0.5665,  0.1616],
        [ 0.8111, -0.2087, -0.0297]])
tensor([[7.0591e-01, 2.8874e-02, 3.6873e-04],
        [9.4325e-02, 6.9774e-02, 1.1342e-02],
        [8.0443e-02, 2.9250e-02, 1.8105e-02]])
tensor([[  0.9225,   0.4161, 209.7059],
        [  2.1177,   6.4444,   4.0573],
        [ 10.0800,   0.3151,   0.8023]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [40]:
TensorA = torch.tensor([[1,2,3], [4,5,6]])
TensorB = torch.tensor([[7,8],[9,10],[11,12]])
result = torch.matmul(TensorA, TensorB)
print(result)

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [44]:

result_1 = torch.add(result, 10)
result_2 = torch.clamp(result_1,max =100)
print(result_1)
print(result_2)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [36]:
x = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
print(x)

result = torch.sum(x, dim=0)
print(result)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
tensor([55, 60, 65, 70, 75])
