<a href="https://colab.research.google.com/github/gksdydcks/Ai/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [4]:
import torch
torch.__version__

'2.5.1+cu121'

In [ ]:
!pip install torchvision torchaudio


#초기화 : 텐서에 특정값을 채워서 생성

#### 1-1 초기화 되지 않은 Tensor

In [5]:
import cv2
import numpy as np
x = torch.empty(4,2)  #2d텐서 (row,column)
print(x)

tensor([[ 5.4689e-18,  4.4267e-41],
        [ 5.4689e-18,  4.4267e-41],
        [-2.8000e+04,  3.1114e-41],
        [-2.8000e+04,  3.1114e-41]])


#### 1-2 상수로 초기화 된 Tensor

In [ ]:
x = torch.zeros(4,2, dtype=torch.long)  #데이터 타입 지정
y = torch.ones(2,4, dtype=torch.double)
print(x,y)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


#### 1-3 무작위로 초기화된 Tensor

In [ ]:
x=torch.rand(4,2)
y=torch.randn(2,3)
print(x,y)

tensor([[0.8186, 0.2628],
        [0.3714, 0.7915],
        [0.2621, 0.1282],
        [0.7787, 0.9399]]) tensor([[-0.1942, -0.3488, -0.7999],
        [-0.7505,  1.4071,  0.6067]])


#### 1-4. 직접 입력한 값으로 초기화

In [ ]:
x = torch.tensor([1,2.5])
print(x)

tensor([1.0000, 2.5000])


#### 1-5. Numpy 배열로 부터 초기화

In [ ]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)

b = torch.tensor([1,2,3,4,5])#numpy array로 변환
new_nd = b.numpy()
new_nd[2] = 100 #[2번째 바꿈]
print(new_nd)


[  1   2 100   4   5]


#### 1-6. 특정 텐서와 같은 타입, 무작위로 값을 채움

In [ ]:
a =torch.ones(3,4,dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float)
#b = torch.zeors_like(a, dtype=torch.float) #0출력
print(b)

tensor([[0.2113, 0.2767, 0.5380, 0.9465],
        [0.3174, 0.0388, 0.9520, 0.1931],
        [0.5190, 0.2859, 0.5029, 0.9802]])


In [1]:
!git add test1.ipynb


fatal: not a git repository (or any of the parent directories): .git


#### 1-7. Tensor의 속성

In [6]:
tensor = torch.rand(3,4)
print(tensor.size())#모양
print(tensor.shape)#모양
print(tensor.dtype)#자료형
print(tensor.device)#장치

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


#### 1-8. 특정 타입의 Tensor 생성

In [9]:
tensor = torch.rand(3,4,dtype=torch.float64)
print(tensor.dtype)
ft = torch.FloatTensor([1,2,3])
print(ft.dtype)

tensor = torch.tensor([1,2,3], dtype=torch.int32)
print(tensor.dtype)


torch.float32
torch.int32


#### 1-9. 데이터 타입 캐스팅

In [10]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())
int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


#### 1-10. CUDA Tensor

In [12]:
print(torch.cuda.is_available())

True
